name: Generate Gradle Wrapper

on:
  workflow_dispatch: # تشغيل يدوي

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Gradle CLI
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Generate Gradle Wrapper (8.2)
        run: gradle wrapper --gradle-version 8.2 --distribution-type all

      - name: Upload Wrapper Files
        uses: actions/upload-artifact@v4
        with:
          name: gradle-wrapper
          path: |
            gradlew
            gradlew.bat
            gradle/wrapper/gradle-wrapper.properties
            gradle/wrapper/gradle-wrapper.jar
